# Generated by Django 5.1.3 on 2024-11-29 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareduri',
            name='Token',
            field=models.CharField(blank=True, default='ksm9e))vng49ip)%3-qlh8(rg8)##!upe6%ft2*94j=k7z@2=v', editable=False, max_length=50, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='usersite',
            name='CurrentSize',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Занятое место (гб)'),
        ),
    ]
