# Generated by Django 5.1.2 on 2024-11-04 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'verbose_name': 'Логи', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='filefolder',
            options={'verbose_name': 'Идентификатор файлов и папок', 'verbose_name_plural': 'Идентификатор файлов и папок'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Папка', 'verbose_name_plural': 'Папки'},
        ),
        migrations.AlterModelOptions(
            name='premission',
            options={'verbose_name': 'Права доступа', 'verbose_name_plural': 'Права доступа'},
        ),
        migrations.AlterModelOptions(
            name='shareduri',
            options={'verbose_name': 'Ссылка доступа', 'verbose_name_plural': 'Ссылки доступа'},
        ),
        migrations.AlterModelOptions(
            name='teg',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='folder',
            name='IDUser',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь(и)'),
        ),
    ]
