# Generated by Django 5.1.2 on 2024-11-23 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teg_colot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teg',
            name='Colot',
        ),
    ]
