# Generated by Django 5.1.2 on 2024-11-01 11:16

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_usersummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSummary',
        ),
        migrations.CreateModel(
            name='UserSummary',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
