# Generated by Django 5.1.3 on 2024-12-14 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_shareduri_token_alter_usersite_currentsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareduri',
            name='Token',
            field=models.CharField(blank=True, default='n)=x)%6bkkq%%%26rp!c85diq9%97l_l3p72%!$6@q5jt5cfub', editable=False, max_length=50, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='usersite',
            name='MaxSize',
            field=models.IntegerField(blank=True, default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доступное место (гб)'),
        ),
    ]
