# Generated by Django 5.1.2 on 2024-11-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_shareduri_idpremission_alter_shareduri_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareduri',
            name='Premissions',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='shareduri',
            name='Token',
            field=models.CharField(blank=True, default='&fgf9u7r08mj6vwdj3vrx11ex8_ex5#t(+a(uadjh6qhas15n$', editable=False, max_length=50, verbose_name='Токен'),
        ),
    ]
