# Generated by Django 5.1.2 on 2024-11-25 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shareduri_premissions_alter_shareduri_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareduri',
            name='IDFileFolder',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.filefolder', verbose_name='Папка/Файл'),
        ),
        migrations.AlterField(
            model_name='shareduri',
            name='IDSender',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель ссылки'),
        ),
        migrations.AlterField(
            model_name='shareduri',
            name='Premissions',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='shareduri',
            name='Token',
            field=models.CharField(blank=True, default='_$m2p=-%)uqog+*3$sx_lhy0-+*@&^i$t2s5+6_gs9j&5y(d#a', editable=False, max_length=50, verbose_name='Токен'),
        ),
    ]
