# Generated by Django 5.1.2 on 2024-11-15 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_file_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefolder',
            name='IDTeg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teg', verbose_name='Тег'),
        ),
    ]
