# Generated by Django 5.1.2 on 2024-11-25 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_shareduri_idfilefolder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareduri',
            name='IDFileFolder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filefolder', verbose_name='Папка/Файл'),
        ),
        migrations.AlterField(
            model_name='shareduri',
            name='IDSender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель ссылки'),
        ),
        migrations.AlterField(
            model_name='shareduri',
            name='Premissions',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shareduri',
            name='Token',
            field=models.CharField(blank=True, default='a2!9xbw09k_r20i-ef+p*rl32h((1&q+fe=@+2990t!mg#y_m*', editable=False, max_length=50, verbose_name='Токен'),
        ),
    ]
