name: Kursach test lol kek eshkere

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install flake
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Check errors
      run: |
        flake8 . --count --show-source --statistics