name: Kursach test lol kek eshkere

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

      run: |
        python -m pip install --upgrade pip
        pip install flake8

      run: |
        flake8 . --count --show-source --statistics