name: Kursach test lol kek eshkere

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install flake
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Check error
      run: |
        flake8 . --count --show-source --statistics --select=E9,F63,F7 --ignore=E501,W292,E401,W391,E265